-------------------------------------------------------------------------------
Test set: api.testSuite.ApiSuiteTest
-------------------------------------------------------------------------------
Tests run: 14, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 11.104 sec <<< FAILURE! - in api.testSuite.ApiSuiteTest
ct06_deveRetornarSucessoLimiteSuperiorIntervaloPt(api.testcases.ApiPtTest)  Time elapsed: 0.478 sec  <<< FAILURE!
java.lang.AssertionError: valor do intervalo diferente do retornado
	at org.junit.Assert.fail(Assert.java:88)
	at api.utils.ReportLog.enviaRelatorio(ReportLog.java:33)
	at api.testcases.ApiPtTest.ct06_deveRetornarSucessoLimiteSuperiorIntervaloPt(ApiPtTest.java:143)

ct01_deveRetornarErroAbaixoIntervaloEn(api.testcases.ApiEnTest)  Time elapsed: 0.424 sec  <<< FAILURE!
java.lang.AssertionError: Status Code diferente do retornado
	at org.junit.Assert.fail(Assert.java:88)
	at api.utils.ReportLog.enviaRelatorio(ReportLog.java:30)
	at api.testcases.ApiEnTest.ct01_deveRetornarErroAbaixoIntervaloEn(ApiEnTest.java:64)

ct02_deveRetornarSucessoLimiteInferiorIntervaloEn(api.testcases.ApiEnTest)  Time elapsed: 0.474 sec  <<< FAILURE!
java.lang.AssertionError: Falha no padrão do parametro
	at org.junit.Assert.fail(Assert.java:88)
	at api.utils.ReportLog.enviaRelatorio(ReportLog.java:44)
	at api.testcases.ApiEnTest.ct02_deveRetornarSucessoLimiteInferiorIntervaloEn(ApiEnTest.java:79)

ct07_deveRetornarErroAcimaIntervaloEn(api.testcases.ApiEnTest)  Time elapsed: 0.423 sec  <<< FAILURE!
java.lang.AssertionError: Status Code diferente do retornado
	at org.junit.Assert.fail(Assert.java:88)
	at api.utils.ReportLog.enviaRelatorio(ReportLog.java:30)
	at api.testcases.ApiEnTest.ct07_deveRetornarErroAcimaIntervaloEn(ApiEnTest.java:159)

